## Data Encoding

1. Nominal/OHE Encoding
2. Label and Ordinal Encoding
3. Target Guided Ordinal Encoding

In [80]:
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, OrdinalEncoder

### Nominal/OHE Encoding
One hot encoding, also known as nominal encoding, is a technique used to represent categorical data as numerical data, which is more suitable for machine learning algorithms. In this technique, each category is represented as a binary vector where each bit corresponds to a unique category. For example, if we have a categorical variable "color" with three possible values (red, green, blue), we can represent it using one hot encoding as follows:

1. Red: [1, 0, 0]
2. Green: [0, 1, 0]
3. Blue: [0, 0, 1]

In [81]:
df=pd.DataFrame({
  'color':['red','green','blue','green','red'],
})
df

   color
0    red
1  green
2   blue
3  green
4    red

In [82]:
#Create an instance of the OneHotEncoder for the 'color' column
encoder = OneHotEncoder()

In [83]:
encoded_data = encoder.fit_transform(df[['color']]).toarray()

In [84]:
categories=encoder.get_feature_names_out()
categories

array(['color_blue', 'color_green', 'color_red'], dtype=object)

In [85]:
encoded_df=pd.DataFrame(encoded_data, columns=categories)
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0

In [86]:
pd.concat([df, encoded_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1  green         0.0          1.0        0.0
2   blue         1.0          0.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0

### Label Encoding 
Label encoding and ordinal encoding are two techniques used to encode categorical data as numerical data.

Label encoding involves assigning a unique numerical label to each category in the variable. The labels are usually assigned in alphabetical order or based on the frequency of the categories. For example, if we have a categorical variable "color" with three possible values (red, green, blue), we can represent it using label encoding as follows:

1. Red: 0
2. Green: 1
3. Blue: 2

In [87]:
label_encoder=LabelEncoder()

In [88]:
label_encoder.fit_transform(df[['color']])

d:\150-days-of-ai-and-machine-learning\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 1, 0, 1, 2])

In [89]:
label_encoder.transform([['red']])

d:\150-days-of-ai-and-machine-learning\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

### Ordinal Encoding
It is used to encode categorical data that have an intrinsic order or ranking. In this technique, each category is assigned a numerical value based on its position in the order.

In [90]:
rating_df=pd.DataFrame({
  'rating':['low','medium','high','medium','low']
})
rating_df

   rating
0     low
1  medium
2    high
3  medium
4     low

In [91]:
encoder=OrdinalEncoder(categories=[['low','medium','high']]) #Categories should be in order of low to high

In [92]:
encoder.fit_transform(rating_df[['rating']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.]])

In [93]:
encoder.transform([['medium']])

d:\150-days-of-ai-and-machine-learning\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[1.]])

## Target Guided Ordinal Encoding 
It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category. This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [94]:
df=pd.DataFrame({
  'city':['Kathmandu','Pokhara','Lalitpur','Pokhara','Kathmandu','Biratnagar'],
  'room_price':[1000, 2000, 1500, 2500, 1200, 1800]
})
df

         city  room_price
0   Kathmandu        1000
1     Pokhara        2000
2    Lalitpur        1500
3     Pokhara        2500
4   Kathmandu        1200
5  Biratnagar        1800

In [95]:
mean_price=df.groupby('city')['room_price'].mean().to_dict()

In [96]:
mean_price

{'Biratnagar': 1800.0,
 'Kathmandu': 1100.0,
 'Lalitpur': 1500.0,
 'Pokhara': 2250.0}

In [97]:
df['city_encoded']=df['city'].map(mean_price)
df

         city  room_price  city_encoded
0   Kathmandu        1000        1100.0
1     Pokhara        2000        2250.0
2    Lalitpur        1500        1500.0
3     Pokhara        2500        2250.0
4   Kathmandu        1200        1100.0
5  Biratnagar        1800        1800.0

In [98]:
df.drop('city', axis=1, inplace=True)
df

   room_price  city_encoded
0        1000        1100.0
1        2000        2250.0
2        1500        1500.0
3        2500        2250.0
4        1200        1100.0
5        1800        1800.0